### ISSUE TITLE
Plan of action!

### ISSUE THREAD

**Issue by nblumhardt** [autofac/autofac-analysis#2]
Here's where we are today:

![image](https://cloud.githubusercontent.com/assets/342712/7198957/f4fc968c-e533-11e4-8bff-877de9443edf.png)

Here's what folks effectively want:

http://stackoverflow.com/questions/18578942/how-can-i-log-all-resolve-requests-to-autofac-container

This thread might be a good place to start a new plan. CC @gkinsman

**Comment by nblumhardt** [comment]
**Where the current codebase came from**

The code here is originally from an application, Whitebox: https://code.google.com/p/whitebox/. Because Whitebox ran in another process, it was necessary to stream a series of events to it from the Autofac container, rather than work synchronously.

On the one hand, this makes the code quite complicated, and there are a lot of anachronisms in there: types are passed around as strings which are later parsed etc., there's a fairly redundant "transport" layer, and nothing is very "direct". Being highly concurrent within a WPF GUI required some tactics for marshaling between threads (see `ActionEvent`) ... and so-on.

On the other hand, it's very hygenic and robust. Apart from some CPU cost it has very little impact on the executing app. It can run analyses that cross thread boundaries, and it's somewhat immune to locking or leaking.

Perhaps the biggest downside of the design however (apart from the complexity) is that the events it produces aren't synchronously emitted, so correlating the output with application events requires some kind of id like the "resolve operation id" being emitted above.

I'm open to starting with a clean slate, but getting back to the current level of possible functionality would also be non-trivial :)

**What does it do?**

Besides emitting events during registration and resolve operations, the library:
- Can build a complete depiction of the object graph created by a resolve event, including "looked-up" dependencies, not just those that were newly emitted
- Can detect long-lived lifetime scopes
- Detects out-of-order lifetime scope disposal
- Detects leaky behaviour where a component is repeatedly resolved from the root scope

**What should it do?**

I think "Autofac Copilot" would be a better name for this project. Rather than show the developer everything going on in the container, working at one level of abstraction higher to show the developer how the container is working within their application seems more useful.

E.g. rather than tracing resolve operations the way the options in the SO thread reveal, emitting a description of the tree at the completion of an entire resolve operation would provide the same data but in a single structured event.

"Autofac Navigator" would also be a great name. When an instance of a component is looked up, tracing that component back to when it was instantiated, or to the registration exposing it, would be great. Via Seq or a similar document store, being able to query for all implementations of a service or view the services exposed by a component would be great. As would be checking whether a component is ever resolved, by correlating from its id at registration time.

Rather than make the user build up their mental model from a trace of events, the project can do that heavy lifting for them as much as possible.

**How could/should it work?**

If we kept roughly the same codebase, I think the general usage would be:
- It'd be installed as a NUPKG and conditionally registered into Autofac as a module
- It'd default to the static Serilog logger, but accept an `ILogger` optionally
- It's not something that's ever enabled in prod, except in times of dire need
- It's always on in development, so would need to be conservative about event levels (perhaps trace-level stuff could go out at `Debug` but only resolve-start/resolve-finish and component registration events at `Information`)

**What would need to happen?**
- [ ] Decide on whether pushing forward from here makes sense :-)
- [ ] If so, decide whether to preserve the ability to run out-of-proc (I'd vote "no")
- [ ] Convert to a PLIB?
- [ ] Give it a better name?
- [ ] Cut out cruft (named pipes support, make sure warnings etc. use message templates properly, perhaps get rid of the "type discovery" mechanism in favour of `Type` objects)
- [ ] Make sure we shut down cleanly
- [ ] More... much more...

But, this has been itching to turn into a kick-ass dev tool for ages, it'd be wonderful to see it made real.

**Comment by nblumhardt** [comment]
To get an idea of just how much is in here.. take a look at `Handle(ItemCompletedEvent<ResolveOperation> applicationEvent)` in https://github.com/autofac/autofac-analysis/blob/master/src/Autofac.Analysis/Display/EventWriter.cs#L53 with a debugger.

At the completion of a resolve operation, you can investigate the entire object graph that was resolved, the lifetimes of all the components that were involved in it, and so-on across the entire container :-)

**Comment by tillig** [comment]
Something to consider might be two different event "types":
- Diagnostic events - the ones that output the resolve trees and so on to help people figure out issues or trace execution.
- Performance events - how many resolutions are happening per second, how long a resolution takes, etc.

Having some timings or perf-related info might help folks better provide information to us when claiming their application is falling apart due to some lock or other Autofac core behavior even though they've not actually attached a profiler to the app.

If that's interesting, it might be that there are two "loggers" you use - one for each event type. Perf type events might be better written (in Windows) to ETW since a lot of perf stuff already flows through there, though being pluggable would be cool because I can see it might also be interesting to pipe that sort of stuff to a statsd server or the like to get statistics graphs on the data.

That said... maybe the ETW/perf events are something that should be done in Autofac core by default and only use this for diagnostics?

**Comment by alexmg** [comment]
Good point about diagnostic versus performance, though I think something like
Serilog would work well for both. I've been using SerilogMetrics without issue
(though thinking about adding histogram to it).

https://www.nuget.org/packages/SerilogMetrics/

Nice thing with Serilog is that you get your choice of sinks for storing the
results. I've been putting them in Seq and Elasticsearch. Performance results in
Elasticseach with Kibana for dashboards is sweet.

Been thinking about turning the resolve events into an RX stream too. Throw a
resolve Id into the mix and correlation would be a piece of cake. The same could
be done with Serilog log entries too though. Love my structured logging
especially with lots of service bus sagas and correlation ids on messages. No
reason for a resolve operation to be any different. :)

On Sat, Apr 18, 2015 at 12:46 am, Travis Illig < notifications@github.com [notifications@github.com] > wrote:
Something to consider might be two different event "types":
- Diagnostic events - the ones that output the resolve trees and so on to help
  people figure out issues or trace execution.
- Performance events - how many resolutions are happening per second, how long
  a resolution takes, etc.

Having some timings or perf-related info might help folks better provide
information to us when claiming their application is falling apart due to some
lock or other Autofac core behavior even though they've not actually attached a
profiler to the app.

If that's interesting, it might be that there are two "loggers" you use - one
for each event type. Perf type events might be better written (in Windows) to
ETW since a lot of perf stuff already flows through there, though being
pluggable would be cool because I can see it might also be interesting to pipe
that sort of stuff to a statsd server or the like to get statistics graphs on
the data.

—
Reply to this email directly or view it on GitHub
[https://github.com/autofac/autofac-analysis/issues/2#issuecomment-94000496] .[https://github.com/notifications/beacon/AAIA3f_r8CRshimqAvxDgv_RDFJRTkTTks5oARRdgaJpZM4EClUQ.gif]

**Comment by nblumhardt** [comment]
Given it's pretty tough getting some forward trajectory I don't think I can squeeze performance metrics in my current "working set", but something along those lines sounds great.

I'm going to spike just getting two events out - resolve started (with a correlation id) and resolve finished (with an exception or result). Will post back my findings :-)

**Comment by gkinsman** [comment]
I've had some success in generating a log for the `ItemCompletedEvent<ResolveOperation>` event - it just traverses the object graph and logs the dependencies. Unfortunately, of course, it logs them in reverse order. Changing to use a single event would allow control over that, possibly at the expense of display. 

![image](https://cloud.githubusercontent.com/assets/130231/7214978/47126ae6-e606-11e4-8a86-6b7deae33289.png)

The console looks great though!

![image](https://cloud.githubusercontent.com/assets/130231/7215041/1dbbe828-e608-11e4-928f-c6be5be9bb9c.png)

It looks like a completed event fires on error as well, so next I'm going to try and capture that and play around with ideas for displaying resolution failures.

**Comment by nblumhardt** [comment]
Great! Properly displaying resolve failures would be a nice step forward.

Just hacking away and pushed a new changeset, apologies in advance for any merge woes :-)

![image](https://cloud.githubusercontent.com/assets/342712/7215154/3faf5f50-e60d-11e4-97c0-160924d26641.png)

The graph is in there - it's a bit awkward but could be usable, I'm still really rediscovering the whole problem space and digesting a lot of how things fit together.

**Comment by gkinsman** [comment]
I think I also prefer sticking to JSON for the log messages themselves - it makes more sense for non-seq consumers, and having the information in one parse-able place will be useful.

Thinking about the display issue, perhaps there could be a seq app that recognises this message template and does something with them to make them easier to visually scan. Probably not a concern for now, but interesting to think about :).

**Comment by gkinsman** [comment]
I've had a look at exposing the resolution errors, but unfortunately the app throws the exception before the dispatcher handles the queue item and the event doesn't fire. Instead, it appears to continue to try and resolve the dependency, and failing.

My change was to comment out the registration of B, so that resolving C would trigger an exception.

Perhaps we could handle the events synchronously now that  the out of proc support is being removed?

**Comment by nblumhardt** [comment]
Hi all! After some discussion with Alex and Travis, the **new** plan is for me to take this project back to "experimental" mode as a personal project, and for us to see what comes out of this before we make any commitment to support it as a "real" Autofac component. I'm feeling pretty optimistic it'll all come together, so please stick around and keep an eye out for some updates :-)
